server:
  port: 11801
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
            defaultZone: http://192.168.99.117:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: microservicecloud-md5-feign
  rabbitmq:
    username: admin
    password: admin
    host: 192.168.99.117
    port: 5672
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true #开启消费者(程序出现异常的情况下会,捕获异常重试将不生效)进行重试
          max-attempts: 20 #最大重试次数
          initial-interval: 30000 #重试间隔时间（单位毫秒）
          max-interval: 500000  #最大间隔时间（单位毫秒）
          multiplier: 2  #乘子  重试间隔*乘子得出下次重试间隔  30s  60s  120s  240s  此处24s>20s  走20s
          default-requeue-rejected: true # 重试次数超过上面的设置之后是否丢弃（false不丢弃时需要写相应代码将该消息加入死信队列）
    cache:
      connection:
#       缓存连接模式,默认一个连接,多个channel
        mode: channel
#        多个连接,多个channel
#        mode: connection

