eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.117:7001/eureka
#      defaultZone: http://127.0.0.1:7001/eureka
server:
  port: 9000
spring:
  application:
    name: md5-zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false